import type { INodeProperties } from 'n8n-workflow';

export const nodeProperties: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			options: [
				{
					name: 'Get API Schema',
					value: 'getSchema',
					action: 'Get an API schema',
					description: 'Fetch the input and output schema for one API',
				},
				{
					name: 'Get Balance',
					value: 'getBalance',
					action: 'Get wallet balance',
					description: 'Return the remaining wallet balance in USD',
				},
				{
					name: 'Get Request',
					value: 'getRequest',
					action: 'Get a request',
					description: 'Retrieve the current state of a durable Request',
				},
				{
					name: 'List APIs',
					value: 'list',
					action: 'List available data sources',
					description: 'Browse the AnyAPI catalog',
				},
				{
					name: 'Run API',
					value: 'run',
					action: 'Run an API',
					description: 'Execute an API by SKU with a normalized input payload',
				},
				{
					name: 'Search APIs',
					value: 'search',
					action: 'Search available data sources',
					description: 'Run a ranked search over the AnyAPI catalog',
				},
				{
					name: 'Wait for Request',
					value: 'waitRequest',
					action: 'Wait for a request',
					description: 'Poll a durable Request until its result is ready',
				},
			],
			default: 'run',
		},
		{
			displayName: 'Request ID',
			name: 'requestId',
			type: 'string',
			required: true,
			default: '',
			description: 'The resumable AnyAPI Request ID returned by Run API',
			displayOptions: { show: { operation: ['getRequest', 'waitRequest'] } },
		},
		{
			displayName: 'API Name or ID',
			name: 'sku',
			type: 'options',
			typeOptions: { loadOptionsMethod: 'getSkus' },
			required: true,
			default: '',
			description:
				'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			displayOptions: { show: { operation: ['run', 'getSchema'] } },
		},
		{
			displayName: 'Input Mode',
			name: 'inputMode',
			type: 'options',
			noDataExpression: true,
			options: [
				{
					name: 'Fields (From Schema)',
					value: 'fields',
					description: 'Fill typed fields loaded from the selected API schema',
				},
				{
					name: 'Raw JSON',
					value: 'json',
					description: 'Provide the raw JSON payload (supports expressions)',
				},
			],
			default: 'fields',
			displayOptions: { show: { operation: ['run'] } },
		},
		{
			displayName: 'Input',
			name: 'inputFields',
			type: 'resourceMapper',
			noDataExpression: true,
			default: { mappingMode: 'defineBelow', value: null },
			required: true,
			typeOptions: {
				loadOptionsDependsOn: ['sku'],
				resourceMapper: {
					resourceMapperMethod: 'getApiInputSchema',
					mode: 'add',
					fieldWords: { singular: 'input field', plural: 'input fields' },
					addAllFields: true,
					multiKeyMatch: false,
					supportAutoMap: true,
				},
			},
			displayOptions: { show: { operation: ['run'], inputMode: ['fields'] } },
		},
		{
			displayName: 'Input (JSON)',
			name: 'input',
			type: 'json',
			default: '{}',
			description: 'Normalized input payload matching the API input schema',
			displayOptions: { show: { operation: ['run'], inputMode: ['json'] } },
		},
		{
			displayName: 'Options',
			name: 'options',
			type: 'collection',
			placeholder: 'Add Option',
			default: {},
			displayOptions: { show: { operation: ['run'] } },
			options: [
				{
					displayName: 'Return Immediately',
					name: 'returnImmediately',
					type: 'boolean',
					default: false,
					description:
						'Whether to return a Request ID instead of waiting when this API runs asynchronously',
				},
				{
					displayName: 'Fields',
					name: 'fields',
					type: 'string',
					default: '',
					description:
						'Comma-separated keys to keep on each result item (dotted paths allowed). Trims the response; does not change cost.',
				},
				{
					displayName: 'Max Items',
					name: 'maxItems',
					type: 'number',
					typeOptions: { minValue: 0, numberPrecision: 0 },
					default: 0,
					description:
						'Cap the number of result items returned (0 means no cap). Does not change cost.',
				},
				{
					displayName: 'Summary Only',
					name: 'summary',
					type: 'boolean',
					default: false,
					description:
						'Whether to return only a structural outline instead of the full data. Does not change cost.',
				},
			],
		},
		{
			displayName: 'Filters',
			name: 'filters',
			type: 'collection',
			placeholder: 'Add Filter',
			default: {},
			displayOptions: { show: { operation: ['list'] } },
			options: [
				{
					displayName: 'Category',
					name: 'category',
					type: 'string',
					default: '',
					description: 'Category slug to filter by',
				},
			],
		},
		{
			displayName: 'Query',
			name: 'query',
			type: 'string',
			default: '',
			required: true,
			description: 'Words or intent to rank against API names and descriptions',
			displayOptions: { show: { operation: ['search'] } },
		},
		{
			displayName: 'Search Filters',
			name: 'searchFilters',
			type: 'collection',
			placeholder: 'Add Filter',
			default: {},
			displayOptions: { show: { operation: ['search'] } },
			options: [
				{
					displayName: 'Category',
					name: 'category',
					type: 'string',
					default: '',
					description: 'Category slug to scope before ranking',
				},
				{
					displayName: 'Limit',
					name: 'limit',
					type: 'number',
					typeOptions: { minValue: 1 },
					default: 50,
					description: 'Max number of results to return',
				},
				{
					displayName: 'Platform',
					name: 'platform',
					type: 'string',
					default: '',
					description: 'Platform slug to scope before ranking',
				},
			],
		},
];
